### ISSUE TITLE
Whatsapp DarkMode needs update.

### ISSUE THREAD

**Issue by engineerdawood** [obvionaoe/dark#10]
Whatsapp dark mode was working 100% fine.
Please update v2.6.0 to v2.9.0 as of vednoc/dark-whatsapp.

Now it has allot of bugs probably due to update of web version. I have checked vednoc/dark-whatsapp they have updated the dark mode css yesterday to version 2.9.0.

Thanks

**Comment by obvionaoe** [comment]
updated
