### ISSUE TITLE
Rambox alternative

### ISSUE THREAD

**Issue by departet** [obvionaoe/dark#12]
Hey,
looking forward to use this for Rambox. On the readme.md you stated you aren't using it any longer so i was wondering if you found a better alternative with more features.
Thank for the darkmode already!

**Comment by obvionaoe** [comment]
Hey, I dropped Rambox in favour of [Ferdi](https://github.com/getferdi/ferdi), which is more featureful!\\
Such features include: 
* better CSS support
* better dark mode support
* better UI (in my opinion)
* completely free, no paid pro version
* support for Chromium extensions (WIP
* etc...

I hope I helped, and thanks for using dark 🌛

**Comment by departet** [comment]
Sorry for the late answer. Been testing Ferdi the last few days as well. Beside a small whatsapp notification bug it's running really smooth. Thanks again!
