### ISSUE TITLE
CSS no longer working for "new" Facebook Messenger (Rambox)

### ISSUE THREAD

**Issue by blakmarkit** [obvionaoe/dark#14]
**Describe the bug**:
The custom dark mode JS/CSS for Facebook Messenger within Rambox no longer appears to be working. The UI within Messenger appears to have updated within the last day or two (for me) to match the "new" Facebook UI, or at least to more fully align with that style that has been rolling out to users over the last several months. 

**Steps to reproduce**:
Removing, refreshing, re-adding the custom CSS using the recommended steps does not resolve the issue. 

**System information**:
 - OS: Win 10
 - Application: Rambox 0.7.7

**Comment by afonsocraposo** [comment]
Same here on Linux

**Comment by obvionaoe** [comment]
Hi, I am aware of this, Messenger changed all their UI, so with a new WebPack obfuscation all the CSS class names changed.
The theme I was currently using, hasn't updated! 
So I am trying to redo it in such a way that new obfuscations won't break the theme! It may take a little while as I never did a theme myself, and using selectors is a bit of a pain with Facebook's code... 
I will try to be as brief as I can!

Thanks for your patience :smile:

**Comment by afonsocraposo** [comment]
Thank you so much for all your work on this repo. Really appreciate it!

**Comment by jrayga** [comment]
Thanks

**Comment by monkeylove** [comment]
Thanks very much.

**Comment by monkeylove** [comment]
In case anyone is interested, I found updated CSS. Here's how to use it:

Copy the ff. code in

https://pavelmakhov.com/2017/01/rambox-dark-theme/

to the custom code box of the Messenger service in Rambox.

Then copy the CSS code found here (click on "raw" to view the code properly):

https://github.com/ducfilan/Dark-mode-Franz-Ferdi/blob/master/messenger/darkmode.css

and paste it to replace the line "// css goes here".

**Comment by coffee-or-death** [comment]
That doesn't seem to work in Pro 1.5b3. Which version are you using?

> In case anyone is interested, I found updated CSS. Here's how to use it:
> Copy the ff. code in
> https://pavelmakhov.com/2017/01/rambox-dark-theme/
> to the custom code box of the Messenger service in Rambox.
> Then copy the CSS code found here (click on "raw" to view the code properly):
> https://github.com/ducfilan/Dark-mode-Franz-Ferdi/blob/master/messenger/darkmode.css
> and paste it to replace the line "// css goes here".

**Comment by afonsocraposo** [comment]
I found a solution. Add a custom service with the url "https://www.facebook.com/messages/". Then, you can activate the Facebook default dark mode by clicking on the button on the top right corner and enabling it.

**Comment by monkeylove** [comment]
> 
> 
> That doesn't seem to work in Pro 1.5b3. Which version are you using?
> 
> > In case anyone is interested, I found updated CSS. Here's how to use it:
> > Copy the ff. code in
> > https://pavelmakhov.com/2017/01/rambox-dark-theme/
> > to the custom code box of the Messenger service in Rambox.
> > Then copy the CSS code found here (click on "raw" to view the code properly):
> > https://github.com/ducfilan/Dark-mode-Franz-Ferdi/blob/master/messenger/darkmode.css
> > and paste it to replace the line "// css goes here".

I am using Rambox CE 0.7.7.

**Comment by obvionaoe** [comment]
I've added the new CSS to the repo, everything should work as normal now! Sorry for the delay, but exam season is upon me :sweat_smile:
