### ISSUE TITLE
Messenger Theme

### ISSUE THREAD

**Issue by protectorT1** [obvionaoe/dark#2]
When typing a new message the text isn't visible until sent

**Comment by MrRafalSzymanski** [comment]
There has been an update to the messenger style which made the dark theme incompatible.

You can copy the updated dark theme from: https://github.com/auscompgeek/fb-messenger-dark/blob/master/fb-messenger-dark.user.css

**Comment by protectorT1** [comment]
Thanks for the update and the reply, it'll save a lot of spelling mistakes.
