### ISSUE TITLE
Part no longer works

### ISSUE THREAD

**Issue by jerry1970** [obvionaoe/dark#4]
![image](https://user-images.githubusercontent.com/5627407/66721865-6e0c6a80-ee07-11e9-9bbc-824102ed9e48.png)
I assume they changed some selectors but as you can see the edit area and icon background are no longer correct. Typing is white on white.

**Comment by jerry1970** [comment]
Sorry, forgot this, but I doubt it has something to do with Rambox:

Version: 0.6.9
Platform: linux (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by jerry1970** [comment]
Whatsapp also changed something. This is a message in the chat, taking the full width:
![image](https://user-images.githubusercontent.com/5627407/66732550-b43fe900-ee5c-11e9-8c69-a477fabbdc21.png)

**Comment by obvionaoe** [comment]
Messenger is fixed, though there are still some bugs which I'll work on.

I still have to see what changed with WhatsApp, as soon as I find out I'll fix it! Sorry for the delay

**Comment by obvionaoe** [comment]
everything was fixed, let me know if something is not working!
