### ISSUE TITLE
Instagram dark mode has too many space between words

### ISSUE THREAD

**Issue by i-am-ecc** [obvionaoe/dark#9]
I just applied darkmode.css to Instagram Direct in Rambox. It turned the web app dark as expected, but also made the words look strange, as in the picture below:

![Captura de tela de 2020-05-19 15-27-53](https://user-images.githubusercontent.com/64562398/82364262-6b997100-99e5-11ea-91f3-228ce34a71d6.png)

Is there an easy way to fix this?

**Comment by obvionaoe** [comment]
I can't reproduce this issue, could you please give me some more info?

**Comment by i-am-ecc** [comment]
It happens under Rambox 0.75, don't know about FranzOn 7 de jun de 2020 19:50, Luís Guimarães <notifications@github.com> wrote:
I can't reproduce this issue, could you please give me some more info?

**Comment by obvionaoe** [comment]
Yes, I've tested this in Rambox 0.75 and tested every language and still couldn't reproduce this.\
Meanwhile I actually updated the CSS file for this theme, so maybe check and see if the newer version fixes the problem! :first_quarter_moon_with_face:

**Comment by vednoc** [comment]
Might be because of my `--ui-font` variable. Try to change `font_name` to a font that you're 100% sure you have on your system.

```css
    --ui-font: 'font_name', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, Ubuntu, Cantarell, 'Noto Sans', var(--emoji-font), sans-serif;
```

What's weird is that I've never had any issues with it, and in some cases I didn't have all of the fonts from the list except the default `sans-serif` font, which was "DejaVu Sans" on my system.

**Comment by obvionaoe** [comment]
Yeah, it's kind of weird... I didn't think the fonts could cause this!
